### ISSUE TITLE
Requires some modifications

### ISSUE THREAD

**Issue by Kandy-Peter** [Mwapsam/portifolio#8]
Hi @Mwapsam,
Your project looks good and we really appreciate its design, but we would like to suggest you the following modifications:
- It would be nice to remove the fixed position for your mobile icon and also remove its background.
- It would also be nice to fix the entire mobile navbar instead of just the hamburger icon.

**Comment by clintonjosephs** [comment]
Hi @Mwapsam,

I love your project, especially how you applied the spacing for all your elements.  kudos 💯 

There are a few suggestions to make it better though:

- It would be nice if your mobile menu-overlay has a fixed position so that users would not have to scroll past it
- I suggest you put the contact section in the footer area so it would match the Figma requirements
- Good job on laying out the social media icons, don't you think scale transition would make it better?
- CSS pseudo-codes will help reduce the number of CSS classes you use on your elements, this will help improve code readability
- I also suggest you change the title tag text to the [fullname - portfolio] format, to enhance accessibility.
- Finally, it would be nice to add a bit of spacing between the mobile menu-overlay items. This would give it more breathing space.

Good job so far man! Keep up the good work 😊

**Comment by Anny85-code** [comment]
-Your code is awesome , but there are few adjustments I would suggest you apply,
-I would suggest you link all your required sections to the navlinks

-I would suggest instead of background colors for hovering, you use animations.

-I would suggest you clear your codes of inline comment as it makes your code unclean.
